'use client'

import { useState } from 'react'
import { createStoreOrder } from '@/app/actions/commerce'

type Product = { id: string; name: string; category: string; priceCents: number; stock: number }
export function Storefront({ store, products }: { store: { id: string; name: string }; products: Product[] }) {
  const [cart, setCart] = useState<Product[]>([])
  const [checkout, setCheckout] = useState(false)
  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [message, setMessage] = useState('')
  const total = cart.reduce((sum, product) => sum + product.priceCents, 0)
  async function submit(event: React.FormEvent) { event.preventDefault(); setMessage(''); try { await createStoreOrder({ storeId: store.id, customerName: name, customerEmail: email, totalCents: total }); setCart([]); setCheckout(false); setName(''); setEmail(''); setMessage('Order received. Thank you!') } catch { setMessage('Could not place the order. Check your details and try again.') } }
  return <><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map((product) => <article key={product.id} className="rounded-2xl border border-border bg-card p-5"><div className="flex aspect-[4/3] items-center justify-center rounded-xl bg-muted text-4xl font-semibold text-primary/40">{product.name.slice(0, 1)}</div><div className="mt-5 flex items-start justify-between gap-4"><div><h2 className="font-semibold">{product.name}</h2><p className="mt-1 text-sm text-muted-foreground">{product.category}</p></div><p className="font-medium">${(product.priceCents / 100).toFixed(2)}</p></div><button onClick={() => setCart((current) => [...current, product])} disabled={product.stock < 1} className="mt-5 w-full rounded-lg bg-primary px-4 py-2.5 text-sm font-medium text-primary-foreground disabled:opacity-40">{product.stock < 1 ? 'Sold out' : 'Add to cart'}</button><p className="mt-3 text-center text-xs text-muted-foreground">{product.stock} available</p></article>)}</div>{message && <p className="mt-6 rounded-lg bg-primary/10 p-4 text-sm text-primary">{message}</p>}{cart.length > 0 && <div className="fixed bottom-5 right-5 z-40 flex items-center gap-4 rounded-xl border border-border bg-card p-4 shadow-xl"><span className="text-sm font-medium">{cart.length} item{cart.length === 1 ? '' : 's'} · ${(total / 100).toFixed(2)}</span><button onClick={() => setCheckout(true)} className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Checkout</button></div>}{checkout && <div className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/25 p-4" onClick={() => setCheckout(false)}><form onSubmit={submit} onClick={(event) => event.stopPropagation()} className="w-full max-w-md rounded-2xl border border-border bg-card p-6 shadow-2xl"><h2 className="text-xl font-semibold">Complete your order</h2><p className="mt-1 text-sm text-muted-foreground">Total ${(total / 100).toFixed(2)}</p><div className="mt-6 space-y-4"><input required value={name} onChange={(event) => setName(event.target.value)} placeholder="Your name" className="w-full rounded-lg border border-input bg-background px-3 py-2.5 text-sm" /><input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Email address" className="w-full rounded-lg border border-input bg-background px-3 py-2.5 text-sm" /></div><button className="mt-6 w-full rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Place order</button></form></div>}</>
}
